name       : eom
version    : 1.22.0
release    : 14
source     :
    - https://github.com/mate-desktop//eom/archive/v1.22.0.tar.gz : 662251e2ae169529658c2bf1db27a37b0bc6f396322b7e6d0aea1c8ba3332d02
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Eye Of MATE - Image Viewer
description: |
    Eye Of MATE is the Image Viewer of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(mate-desktop-2.0)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
