name       : eom
version    : 1.18.2
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.18/eom-1.18.2.tar.xz : 0755a43f48fe1a09b826cdd6ed239631f5e4f9163ccb481362534d8fcf3bda02
license    : GPL-2.0
component  : desktop.mate
summary    : Eye Of MATE - Image Viewer
description: |
    Eye Of MATE is the Image Viewer of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(x11)
    - itstool
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
