name       : eom
version    : 1.27.0
release    : 32
source     :
    - https://github.com/mate-desktop/eom/releases/download/v1.27.0/eom-1.27.0.tar.xz : a2f7f91452583be98744c175f4178acd1688e2c869c2aefc5a1156044757353c
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Eye Of MATE - Image Viewer
description: |
    Eye Of MATE is the Image Viewer of the MATE Desktop
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(mate-desktop-2.0)
    - itstool
setup      : |
    %configure --disable-static \
        --enable-gtk-doc \
        --enable-thumbnailer \
        --without-gdk-pixbuf-thumbnailer
build      : |
    %make
install    : |
    %make_install
