name       : eom
version    : 1.20.1
release    : 11
source     :
    - https://pub.mate-desktop.org/releases/1.20/eom-1.20.1.tar.xz : 35375d5d55128e03c9a4f9e5559878873275c6e182b159058767180ca449347d
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Eye Of MATE - Image Viewer
description: |
    Eye Of MATE is the Image Viewer of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
