name       : eom
version    : 1.22.1
release    : 15
source     :
    - https://github.com/mate-desktop/eom/archive/v1.22.1.tar.gz : 5a73e07a76f9c9e2844728946379cc2bf7c6bdac0813dfeb70c214560823a366
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Eye Of MATE - Image Viewer
description: |
    Eye Of MATE is the Image Viewer of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(mate-desktop-2.0)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
