name       : eom
version    : 1.24.2
release    : 27
source     :
    - https://github.com/mate-desktop/eom/releases/download/v1.24.2/eom-1.24.2.tar.xz : eead30072ada9a697c0284ee0ac72f0cd80cf01eff43e1c260873718f2643223
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Eye Of MATE - Image Viewer
description: |
    Eye Of MATE is the Image Viewer of the MATE Desktop
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(mate-desktop-2.0)
    - itstool
setup      : |
    %configure --disable-static \
        --enable-gtk-doc \
        --enable-thumbnailer \
        --without-gdk-pixbuf-thumbnailer
build      : |
    %make
install    : |
    %make_install
