name       : eom
version    : 1.16.0
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.16/eom-1.16.0.tar.xz : 974356c10bf96b974b777614d5d6f88f982a6c9ab3735d9397b4a33a6812c4fe
license    : GPL-2.0
component  : desktop.mate
summary    : Eye Of MATE - Image Viewer
description: |
    Eye Of MATE is the Image Viewer of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(x11)
    - libjpeg-turbo-devel
    - itstool
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
