name       : eom
version    : 1.14.2
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/eom-1.14.2.tar.xz : ffdd2a229e6a1c3a133b3d4e981b820e9573983e4195cc66b98300ed6113fda2
license    : GPL-2.0
component  : desktop.mate
summary    : Eye Of MATE - Image Viewer
description: |
    Eye Of MATE is the Image Viewer of the MATE Desktop
builddeps  :
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(x11)
    - libjpeg-turbo-devel
    - itstool
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
