name       : eom
version    : 1.22.2
release    : 17
source     :
    - https://github.com/mate-desktop/eom/archive/v1.22.2.tar.gz : f1c158b743f6ff588b0739ee02ce1c5984a00f95628eebc574532248062191eb
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Eye Of MATE - Image Viewer
description: |
    Eye Of MATE is the Image Viewer of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(mate-desktop-2.0)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
